/* ═══════════════════════════════════════════════════════════
   BSC Collections — Cinematic Scroll Data
   ═══════════════════════════════════════════════════════════ */
const BSC_COLLECTIONS = [
  {
    id: "women",
    title: "Women's Collection",
    kicker: "01 — FROM THE AISLE",
    description: "Kanjivarams silks · ethnic party wear · dress materials · casuals · workwear",
    image: "/assets/img/collection-women.jpg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#CA2125",
    floaters: ["silk", "hanger", "fold"],
  },
  {
    id: "men",
    title: "Men's Collection",
    kicker: "02 — FROM THE AISLE",
    description: "Formals · office wear · shirts · trousers · ethnic sets · suiting fabrics",
    image: "/assets/img/collection-men.jpg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#203A85",
    floaters: ["watch", "tie", "hanger"],
  },
  {
    id: "kids",
    title: "Kids & Teens",
    kicker: "03 — FROM THE AISLE",
    description: "Back-to-school · festive sets · first-birthday silks · nightwear · playwear",
    image: "/assets/img/collection-kids.jpg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#C77F2B",
    floaters: ["star", "tag", "shape"],
  },
  {
    id: "wedding",
    title: "Wedding Occasion",
    kicker: "04 — THE BRIDAL WING",
    description: "Complete trousseau — bridal groom silks, family occasion wear, jewellery pairs, gifting",
    image: "/assets/img/collection-wedding.jpg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#8E1D26",
    floaters: ["ring", "gift", "silk"],
  },
  {
    id: "home",
    title: "Home Furnishings",
    kicker: "05 — FOR THE HOME",
    description: "Linen curtains · bedspreads · cushions · mats dhurries · festive décor",
    image: "/assets/img/collection-home.jpg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#3B5BA8",
    floaters: ["cushion", "lamp", "fabric"],
  },
  {
    id: "dress-materials",
    title: "Dress Materials & Fabrics",
    kicker: "06 — UNSTITCHED",
    description: "Unstitched suits, silks and cottons by the metre",
    image: "/assets/img/hero-fabric.jpg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#CA2125",
    floaters: ["wave", "roll", "thread"],
  },
  {
    id: "jewellery",
    title: "Imitation Jewellery",
    kicker: "07 — ADORN",
    description: "Bridal pairs · temple sets · everyday sparkle",
    image: "/assets/img/collection-jewellery.svg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#C77F2B",
    floaters: ["necklace", "ring", "box"],
  },
  {
    id: "cosmetics",
    title: "Cosmetics",
    kicker: "08 — BEAUTY",
    description: "Beauty counters with trusted names",
    image: "/assets/img/collection-cosmetics.svg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#CA2125",
    floaters: ["bottle", "compact", "perfume"],
  },
  {
    id: "footwear",
    title: "Footwear",
    kicker: "09 — STEP IN",
    description: "Formal to festive, for all ages",
    image: "/assets/img/collection-footwear.svg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#203A85",
    floaters: ["shoe", "sole", "lace"],
  },
  {
    id: "accessories",
    title: "Fashion Accessories",
    kicker: "10 — FINISHING TOUCH",
    description: "Bags, belts, dupattas — the finishing touch",
    image: "/assets/img/collection-accessories.svg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#8E1D26",
    floaters: ["bag", "belt", "scarf"],
  },
  {
    id: "brands",
    title: "Curated Brands",
    kicker: "11 — BEYOND BSC",
    description: "Alongside BSC's own trusted offerings — greater choice across styles, needs and occasions",
    image: "/assets/img/collection-brands.svg",
    direction: "left",
    cta: "VIEW IN STORE →",
    accent: "#203A85",
    floaters: ["logo", "label", "tag"],
  },
  {
    id: "tailoring",
    title: "Expert Tailoring",
    kicker: "12 — MADE TO FIT",
    description: "For men & women — fit-on-approval stitching",
    image: "/assets/img/collection-tailoring2.svg",
    direction: "right",
    cta: "VIEW IN STORE →",
    accent: "#CA2125",
    floaters: ["scissors", "tape", "spool"],
  },
];

window.BSC_COLLECTIONS = BSC_COLLECTIONS;
